name = "we-need-your-help-api"
main = "worker.mjs"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "we-need-your-help-db"
database_id = "c54c5ab5-7299-4b95-aafb-dfddfb831a65"